### ISSUE TITLE
feat: auth error

### ISSUE THREAD

**Issue by mssjcksn** [ArchonsDev/flask-pointwatch-api#11]
I tried to send a post request for registering an account but after multiple reviews, it just wouldn't show "Registration successful!" and it's just stuck in the form page. 

The image below shows the console log & requests sent. I've noticed that in the requests it says that I sent an **OPTIONS** request? The **POST** request was tested using Postman (which works) so I wasn't really sure why it says **OPTIONS** whenever I send a request thru my application
![image](https://github.com/ArchonsDev/flask-pointwatch-api/assets/62651994/4e34f9b7-c4d9-459c-9966-5c4162f50baa)

My code:
![image](https://github.com/ArchonsDev/flask-pointwatch-api/assets/62651994/82e4e1f5-02d0-4f3d-8eea-fe98fb560b88)

Stuff GPT said (cropped lol):
![image](https://github.com/ArchonsDev/flask-pointwatch-api/assets/62651994/52a975f0-56c0-4c45-a4b7-dc04128e7275)

lmk if the issue is really just me :)

**Comment by cxrvxxxx** [comment]
This issue should have been fixed with Merge #12 as CORS support was added with this update

**Comment by mssjcksn** [comment]
Not yet :(
