### ISSUE TITLE
Report Generation

### ISSUE THREAD

**Issue by gilberx** [ArchonsDev/flask-pointwatch-api#123]
Ana si Dawn ipa change kuno ang status "rejected" to "Fo Revision"
![image](https://github.com/user-attachments/assets/49fb3cab-370f-4758-81da-e54be4f5a082)

**Comment by mssjcksn** [comment]
## Requested changes for the following reports:
- [ ] SWTDs Report. 
Check the [sample](https://docs.google.com/spreadsheets/d/11LFVCsdLUOUWcYkIjLlaWDHgxUgLh3K7/edit?usp=sharing&ouid=110672779983809401371&rtpof=true&sd=true) given by HR last semester
![image](https://github.com/user-attachments/assets/16c75e81-8d99-446f-811e-1e1d52c34ad6)

- [ ] Validation Report
![image](https://github.com/user-attachments/assets/7c011c55-4136-4ff5-9b16-80239a0ee9f2)

- [ ] Clearance Report
![image](https://github.com/user-attachments/assets/b2db97f1-8f0d-4c07-b85c-494db180af16)

## Misc
- Another issue worth noting is blank paper generated when head did not validate any SWTDs/clear any employees and if the user has not submitted any SWTDs yet.
