### ISSUE TITLE
Cannot revoke clearance

### ISSUE THREAD

**Issue by mssjcksn** [ArchonsDev/flask-pointwatch-api#134]
Unsure of the details. Is this the correct endpoint from your API bible? `/users/<user_id>/clearances/<clearance_id>?term_id=<term_id>`
If so, where is `clearance_id` used in your code? Or I'm too stupid to understand python 🤠 
![image](https://github.com/user-attachments/assets/db6df467-5203-4d0b-9df0-ef40f4615de1)

**Comment by cxrvxxxx** [comment]
Updated this endpoint just now. It should work now
