### ISSUE TITLE
Deleted SWTDs in exported report in Head Dashboard still counted. 

### ISSUE THREAD

**Issue by owembii** [ArchonsDev/flask-pointwatch-api#136]
![image](https://github.com/user-attachments/assets/d5e17457-df60-412f-93f3-96dfb2917117)
This is Department Head Dashboard

under department members, in pending SWTDs. it still counted the swtd that i deleted (see pic below)
![image](https://github.com/user-attachments/assets/75deecb2-d349-46be-bb9f-159bf4a57832)

Pending SWTDs should be 1 instead of 2, since i deleted the other one and only one is showed in the pic above (^)

**Comment by cxrvxxxx** [comment]
Patched. Please test again.

**Comment by owembii** [comment]
very nice, it is fixed !
