### ISSUE TITLE
GET user request as Admin

### ISSUE THREAD

**Issue by owembii** [ArchonsDev/flask-pointwatch-api#53]
## Request Details
Request Method: `GET`
Endpoint: `/users/<int:id>`
User Permissions: `is_admin`

## Issue
I am able to render the user list for the employees and their SWTDs as seen here
![image](https://github.com/ArchonsDev/flask-pointwatch-api/assets/121376736/7ed21c13-551d-48da-a6b5-7237bb16629e)

but I am unable to get the data of other users but I can for myself (bc im able to log in haha)
![image](https://github.com/ArchonsDev/flask-pointwatch-api/assets/121376736/6d64c812-9b9d-45e0-9a5d-cd661665b972)

For more details, I checked the backend's response and it says that I have insufficient permissions.
![image](https://github.com/ArchonsDev/flask-pointwatch-api/assets/121376736/f88182ac-70b0-47ce-ade4-071665029efa)

### Code for API calls
![image](https://github.com/ArchonsDev/flask-pointwatch-api/assets/121376736/96c28deb-5108-4f4d-b87c-81c8f9d6f990)
- - - - 
![image](https://github.com/ArchonsDev/flask-pointwatch-api/assets/121376736/55221dd5-b454-4f75-87f2-75f82f278a7a)

**Comment by cxrvxxxx** [comment]
Issue is now fixed. See PR #56
