### ISSUE TITLE
PUT Request Update

### ISSUE THREAD

**Issue by mssjcksn** [ArchonsDev/flask-pointwatch-api#54]
## Request Details
Request Method: `PUT`
Endpoint: `swtds/<int:id>/validation/proof`

## Issue
Status does not update when proof changes but it changes when I update other fields of the SWTD (Title, Category, etc).

> Changing of Proof

![image](https://github.com/ArchonsDev/flask-pointwatch-api/assets/62651994/5ab25663-e675-4cd4-bbf7-9ba36bef146d)
![image](https://github.com/ArchonsDev/flask-pointwatch-api/assets/62651994/26103245-f4d6-4022-adab-ffcf027c6c97)

> Changing of SWTD details

![image](https://github.com/ArchonsDev/flask-pointwatch-api/assets/62651994/e96daa88-2349-4d91-ab63-27912386aeab)

**Comment by cxrvxxxx** [comment]
Fixed in PR #57
